version : '2'

services:
  orm-postgres:
      container_name: orm-postgres
      image: pedro151/postgres
      ports:
          - "5432:5432"
      environment:
          POSTGRES_PASSWORD: 123
          POSTGRES_USER: postgres
  orm-mysql:
        container_name: orm-mysql
        image: mysql/mysql-server
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: dao_generator
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  orm-mssql:
        container_name: orm-mssql
        image: microsoft/mssql-server-linux
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: 123
            ACCEPT_EULA: Y
  orm:
      container_name: orm
      image: pedro151/phalcon
      build: .
      volumes:
          - /c/Users:/c/Users
          - /Users/htdocs/orm-generator:/var/www
      working_dir: /var/www
      ports:
          - "80:80"
          - "443:443"
      tty: true
      environment:
        XDEBUG_CONFIG: remote_host=192.168.99.100
      depends_on:
          - orm-postgres
          - orm-mysql
          - orm-mssql
      links:
          - orm-postgres
          - orm-mysql
          - orm-mssql